<a href="https://colab.research.google.com/github/violjii/ML/blob/main/%D0%A1%D0%B5%D1%80%D0%B3%D1%96%D1%94%D0%BD%D0%BA%D0%BE_%D0%B5%D0%BA%D0%B7%D0%B0%D0%BC%D0%B5%D0%BD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Створюємо масив розміром 5x5 з випадковими значеннями від 0 до 1
array = np.random.rand(5, 5)

# Обчислюємо квадратний корінь з кожного елемента масиву
sqrt_array = np.sqrt(array)

# Виводимо початковий масив і масив з квадратними коренями
print("Початковий масив:")
print(array)
print("\nМасив з квадратними коренями:")
print(sqrt_array)


Початковий масив:
[[0.25411856 0.72782845 0.35068526 0.71783651 0.5621554 ]
 [0.34277281 0.636772   0.1758805  0.29076781 0.50775154]
 [0.13742259 0.06341982 0.49441149 0.69110613 0.36210734]
 [0.05548494 0.47923385 0.87782876 0.06389714 0.34394551]
 [0.23882704 0.32869856 0.58581612 0.63774879 0.53637364]]

Масив з квадратними коренями:
[[0.50410174 0.85312863 0.59218685 0.84725233 0.74977023]
 [0.58546802 0.79797995 0.41938109 0.5392289  0.71256686]
 [0.37070553 0.25183292 0.70314401 0.83132793 0.60175355]
 [0.23555242 0.69226718 0.93692516 0.25277884 0.58646868]
 [0.48869934 0.57332239 0.76538625 0.79859175 0.73237534]]
